const db = require('./');
const Prompts = require('./model.js');

var promptsCollection = [
"Who is most likely to become famous?",
"Who is most likely to fart in a car with other passengers?",
"Who is most likely to get arrested?",
"Who is most likely to lock themselves out of their house?",
"Who is most likely to lose their phone?",
"Who is most likely to become a billionaire?",
"Who is most likely to appear on a reality TV show?",
"Who is most likely to fret over small things?",
"Who is most likely to date a celebrity?",
"Who is most likely to rule the world?",
"Who is most likely to survive The Hunger Games?",
"Who is most likely to lose their savings gambling?",
"Who is most likely to be the best kisser?",
"Who is most likely to have children first?",
"Who is most likely to start their own business?",
"Who is most likely to date their own boss?",
"Who is most likely to re-wear underwear?",
"Who is most likely to be on TV?",
"Who is most likely to die first in a zombie apocalypse?",
"Who is most likely to be president?",
"Who is most likely to win an Oscar?",
"Who is most likely to become an alcoholic?",
"Who is most likely to flirt with someone else’s significant other?",
"Who is most likely to have a stalker?",
"Who is most likely to be a stalker?",
"Who is most likely to be Insta-famous?",
"Who is most likely to forget an important date?",
"Who is most likely to move to mars, given the option?",
"Who is most likely to cry while watching a movie?",
"Who is most likely to get into a drunken fight in public?",
"Who is most likely to get drunk after 1 shot?",
"Who is most likely to marry a multi-millionaire?",
"Who is most likely to be a horrible boss?",
"Who is most likely to be scared of roller coasters?",
"Who is most likely to be scared of horror movies?",
"Who is most likely to be a heartbreaker?",
"Who is most likely to be weird in public?",
"Who is most likely to be a best-selling author?",
"Who is most likely to win a Nobel Prize?",
"Who is most likely to fall asleep in class or at work?",
"Who is most likely to talk to animals?",
"Who is most likely to ask too many questions?",
"Who is most likely to become a standup comedian?",
"Who is most likely to be a world traveler?",
"Who is most likely to be a supermodel?",
"Who is most likely to cause a war?",
"Who is most likely to move to another country?",
"Who is most likely to not shower for a week?",
"Who is most likely to take care of others when they are sick?",
"Who is most likely to spend all their money on something stupid?",
"Who is most likely to get drunk tonight?",
"Who is most likely to play a villain in a movie?",
"Who is most likely to play a superhero in a movie?",
"Who is most likely to play a lead role in a movie?",
"Who is most likely to be comedic relief in a dramatic movie?",
"Who is most likely to stay single forever?",
"Who is most likely to be late?",
"Who is most likely to owe you money?",
"Who is most likely to work at Google?",
"Who is most likely to start living in a van?",
"Who is most likely to survive a zombie apocalypse?",
"Who is most likely to go bankrupt?",
"Who is most likely to get sued?",
"Who is most likely to drunk text their ex?",
"Who is most likely to become a meme?",
"Who is most likely to forget where they parked their car?",
"Who is most likely to get punched in the face?",
"Who is most likely to post a bathroom picture on a dating app?",
"Who is most likely to go skinny-dipping?",
"Who is most likely to wander off in a group outing?",
"Who is most likely to own a bar?",
"Who is most likely to be terrible detective?",
"Who is most likely to be a bad driver?",
"Who is most likely to be an alien?",
"Who is most likely to win an eating contest?",
"Who is most likely to embarrass themselves in public?",
"Who is most likely to develop a million dollar app?",
"Who is most likely to get a DUI?",
"Who is most likely to have multiple divorces?",
"Who is most likely to become a motivational speaker?",
"Who is most likely to become a politician?",
"Who is most likely to become a CEO?",
"Who is most likely to be an internet troll?",
"Who is most likely to become a secret agent?",
"Who is most likely to become famous for something stupid?",
"Who is most likely to sleep in until the afternoon?",
"Who is most likely to stay up late playing video games?",
"Who is most likely to stay home on a Friday night?",
"Who is most likely to stay in a toxic relationship?",
"Who is most likely to marry a stranger in Las Vegas?",
"Who is most likely to kiss and tell?",
"Who is most likely to hack their ex’s social media account?",
"Who is most likely to grossly exaggerate the truth?",
"Who is most likely to have a crush on an anime character?",
"Who is most likely to have a messy room?",
"Who is most likely to have the most children?",
"Who is most likely to have the most tattoos?",
"Who is most likely to be the worst cook?",
"Who is most likely to have the most friends on Facebook?",
"Who is most likely to have a kid next?",
"Who is most likely to live until they’re 100?",
"Who is most likely to go on 2 dates in 1 day?",
"Who is most likely to never be single for more than 3 months?",
"Who is most likely to give up on fitness goals?",
"Who is most likely to forgive a cheating partner?",
"Who is most likely to eat fast food tonight?",
"Who is most likely to be a strict parent?",
"Who is most likely to sleep through an alarm?",
"Who is most likely to move back in with their parents?",
"Who is most likely to flake on their friends?",
"Who is most likely to leave dishes in the sink?",
"Who is most likely to fall asleep first at a party?",
"Who is most likely to not get a joke?",
"Who is most likely to get caught telling a lie?",
"Who is most likely to act on a crush?",
"Who is most likely to merge broken code to master branch?",
"Who is most likely to be passive aggressive?",
"Who is most likely to throw up first at a party?",
"Who is most likely to spend the most time on their hair?"
]

const seedData = () => {
  promptsCollection.forEach((prompt, index) => {
    Prompts.create({ id: index + 1, prompt });
  });
  console.log('data seeded');
}

seedData();